# Generated by Django 2.1.4 on 2018-12-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181220_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_at',
            new_name='date',
        ),
    ]
