# Generated by Django 2.1.4 on 2018-12-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181221_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Comment'),
        ),
    ]
