# Generated by Django 2.1.4 on 2018-12-27 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20181227_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchList',
            new_name='WatchItem',
        ),
    ]
