# Generated by Django 2.1.4 on 2019-01-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190121_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
