# Generated by Django 2.1.4 on 2019-01-25 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='translation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
