# Generated by Django 2.1.4 on 2019-01-25 09:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_category_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='translation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
